### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by LNight121** [extremeblackliu/UdonSharpDisassembler#2]
你似乎是在游戏运行时获取的这些东西，其实不需要这么做。完全可以逆向游戏地图的缓存文件，或者使用一些unity编辑器自带的api（推荐使用这个办法，这意味着绝对的安全，但是这也意味着使用者得先下个unity）

**Comment by eeacks** [comment]
的确，我确实知道这一点，在今年3月份的时候我就已经 `新建文件夹` 了，但是自己一直没需求所以进度卡着不动。做Unity内的版本，由于本身不是很熟悉C#，编写稍微有点困难（懒的），所以没去研究。

> 这意味着绝对的安全

你可以使用 [这个](https://github.com/extremeblackliu/VRChat-ALT) 来没有风险地离线测试任何地图，EAC不是问题。

**Comment by LNight121** [comment]
我去年已经开发了unity内的版本，我惊讶于我所做的事情已经有人做过了。不过我受不了看静态的代码，我更喜欢动态的调试。有没有兴趣开发一个模拟器，从加载地图到udon调试（我正在做这个，这意味着下断点和单步调试，简直爽翻）。这也是因为官方已经注意到了玩家在loacltest的肆无忌惮（我记得好像是在封禁盗模时提过），如果哪天localtest也要加载eac就不好玩了。

**Comment by eeacks** [comment]
> 我惊讶于我所做的事情已经有人做过了

我也是，2022年，我发现已经有人做过类似的事情了，但是不符合我的技术栈才开始从头开始研究。

> 不过我受不了看静态的代码，我更喜欢动态的调试。

我甚至完全从汇编中逆向了Terrors of Nowhere，这的确是很麻烦的问题。对于稍微大一点的地图，缺乏调试的情况下很多UdonBehaviour的引用或者其它组件只能预先断言它是什么，再手动验证。

个人而言的确有调试的需求，但是出于抱着能用就暂时这样的心态还是一直没开过新项目。我有兴趣加入你的项目！但是我还没有团队工作的经验。

> 这也是因为官方已经注意到了玩家在loacltest的肆无忌惮（我记得好像是在封禁盗模时提过）

我还不知道这个，已经有人开始这样做了吗？我以为现在还是通过缓存盗模。

> 如果哪天localtest也要加载eac就不好玩了。

从长远来看，的确。不过这一极端行为可能最终受害者反而不是一开始的目标，vrchat一直都在做错事...
